POST http://localhost:3001/api/blogs HTTP/1.1
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1Zjc0ODFmNjExMTFhYjNkY2QwZjYyOGIiLCJpYXQiOjE2MDE1MzM1NDh9.bJjYandPHn4iADRKHdg8ZhiRjaiEEDdbnC1TsiEIZNQ

{
  "title": "Cool Post 123",
  "author": "Robert C. Martin",
  "url": "https://ismelich.tech/",
  "likes": "3"
}